version: '3.7'
services:
  hyperf:
    image: "hyperf/biz-skeleton:latest"
    build:
      context: "."
    ports:
      - 8080:9501
      # - 9601:9601
    volumes:
      - ./:/opt/www
    ulimits:
      nofile:
          soft: 65535
          hard: 65535
    environment:
      APP_ENV: "${APP_ENV:-prod}"
      SCAN_CACHEABLE: "false"
    restart: "always"
    deploy:
      replicas: 1